name: Send Email on Push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Send email notification
      run: |
        curl -X POST https://api.elasticemail.com/v4/emails \
        -H "Content-Type: application/json" \
        -d '{
          "apikey": "98E01DFF3D4C1BAFDF89E0E801431CC12F7353E8417093A5467D345763047472B77785EFD4446315858BB616E883FCB4",
          "from": "alonsoglezjc@gmail.com",
          "to": "juan.alonso@iteso.mx",
          "subject": "Cambios subidos a rama '${{ github.ref_name }}'",
          "bodyHtml": "<p>Hola,</p><p>Se han subido cambios a la rama '${{ github.ref_name }}'.</p><p>Atentamente,<br>Juan Alonso & Carlos Calzada</p>"
        }'

