name: Send Email on Push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Send email notification
      env:
        ELASTICEMAIL_API_KEY: ${{ secrets.ELASTICEMAIL_API_KEY }}
      run: |
        curl -X POST https://api.elasticemail.com/v4/emails \
        -H "Content-Type: application/json" \
        -d "{
          \"apikey\": \"$ELASTICEMAIL_API_KEY\",
          \"from\": \"juan.alonso@iteso.mx\",
          \"to\": \"juan.alonso@iteso.mx\",
          \"subject\": \"Cambios subidos a rama ${{ github.ref_name }}\",
          \"bodyHtml\": \"<p>Hola,</p><p>Se han subido cambios a la rama ${{ github.ref_name }}.</p><p>Atentamente,<br>Juan Alonso & Carlos Calzada</p>\"
        }"
