name: Send Email on Push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Send email notification
      run: |
        curl -X POST https://api.elasticemail.com/v4/emails \
          -d "from=alonsoglezjc@gmail.com" \
          -d "to=juan.alonso@iteso.mx" \
          -d "subject=Cambios subidos a rama ${{ github.ref_name }}" \
          -d "bodyHtml=<p>Hola,</p><p>Se han subido cambios a la rama ${{ github.ref_name }}.</p><p>Atentamente,<br>Juan Alonso & Carlos Calzada</p>" \
          -d "apikey=${{ secrets.ELASTIC_EMAIL_API_KEY }}"
