name: Send Email on Push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Send Mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.elasticemail.com
        server_port: 2525
        username: ${{secrets.SMTP_USERNAME}}
        password: ${{secrets.SMTP_PASSWORD}}
        subject: Cambios subidos a rama ${{github.ref_name}}
        body: |
          <p>Hola,</p>
          <p>Se han subido cambios a la rama ${{github.ref_name}}.</p>
          <p>Atentamente,<br>Juan Alonso & Carlos Calzada</p>
        to: juan.alonso@iteso.mx
        from: juan.alonso@iteso.mx
        content_type: text/html