name: Send Email on Push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.sendgrid.net
        server_port: 587
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: Cambios subidos a rama ${{ github.ref_name }}
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: noreply@mi-repo.com
        body: >
          Hola,

          Se han subido cambios a la rama ${{ github.ref_name }}.

          Atentamente,
          Juan Alonso & Carlos Calzada